import { PORTRAIT_DOT_PATTERNS } from "@/components/identity-portrait-scales.generated"

// Compact form of the product identity stipples (originally traced from the
// final 900 circles in the Uhura and Canopy Figma exports). Each character is
// a 64-level dot scale on the same alphabet the portrait generator uses;
// decodeDotScales in general-purpose-identity.tsx expands them.
export const PRODUCT_DOT_PATTERNS = {
  cmdk: {
    columns: 30,
    levels:
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACITRMOKLDAAAAAAAAAAAAAAAAAAAACFEHZXPKOXSMFAAAAAAAAAAAAAAAKELJIOTcWJQfvqlcAAAAAAAAAAAABHDFLUWcmbTjgurhsnbAAAAAAAAAABHKRelnmVVWRXpxsttqKaAAAAAAAAAMYdjWXUbRNSUvzvnqpukWfAAAAAAATbSPJVKpbMUSelRjRJRAhmqZAAAAAQaaYJSXSUQAJIlWXXW0wMbfclAAAAAQckjQAKNNNOGLWeYx6zuqwUfleAAACbesilqQROANLSiZUq3y5ssiZcpAAAPOQmcRiFUUAATfzeVjh7zzmyfMrDAAXbEQaxrZSSLXmnnppytv440ruilUAAfWIpqoTVbVYngpzu7__ys303w1qgAAXpfZmpRgWRJbpjy17931o2l7wltmAAhmXlrx20SIPVip02777_1cvo23sjAAZdZhDFOlXGAHWUlp66zz5xh9z2qaAANGallMXtujZAAAAHZ5nic26l50kNAABDUfWZf7lTQiKAAAQrkQLvmMy0oAAAAEUiUHMwsnAIAAAIjxVVHmULhvvAAAAYAgUTPAeHFAAMgdllfbAOFGQtSAAAAAANbRZANGFCGJKSbjtdkxQQrpAAAAAAHOfAQAEDdDASSRXXTo2phmuHAAAAAAAYPFHeICIARHEKMRaaMManVAAAAAAAAAMXFNDAAAAAACAPIJOTXWAAAAAAAAAAAKCAAABAAAAAAAHGQbSAAAAAAAAAAAAAELDACAAAAABDIKUBAAAAAAAAAAAAAAAADFGCCCDGHLPDAAAAAAAAAAAAAAAAAAAAABGGHGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  },
  canopy: {
    columns: 30,
    levels:
      "AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAALAAAAAAAHJAAAAAAAAAAAAAAAAAAAFQLAAAAALQOAAAAAAAAAAAAAAAAAAAQTRNAAANVTSEAAAAAAAAAAAAAAAAAEcbXaKALYaWWKAAAAAAAAAAAAAAAAAQlidibObcZYaRAAAAAAAAAAEAAAAAAZrlgmolkgXWdXAAAAAAAAAAJRLCAAAftpkptwnhbafaAAAAAAAFBALbbYNAAfsrnruupleegcAAAHOSUSAAMjkihUCbvuptxukjgghbENXcecaOAAKnrnnkUTtvls0xjgfhjaYlliihdGAAEltrpnjUlunqyvkefhihptqkklbAAAAbtuommcerooutjaehhorqigllRAAAANotmjojZomisrmekiltphejmeDAAAAAZpsqqpXmkhtumjkfoqmhlnjNAAAAAADdrsnsfhmgrrigcfqmglnkSAAAAAAAAGhrqtlalamocccmkklmiPAAAAAAAAAAIjvsoVfWkpcbkpgklbJADLOOIVccSCAJowqZdeokcaqnqqWDGWinnlgelptmUDNnsgcklgXdoqmSFSkrqolhgcilntxnQSpnZgiaWkldLOgrtonhcZbajnqotztabmdgcYafSLVoqmqmmmkdZJXksv030rkhliYdaRTiopggw0yqhaMAAKZmy3764zqfZdZempvxttzxpcODAAAAABLRZiomaUficcehjfaWRMFAAAAAAAAAAAAAAAADkubOEAAAAAAAAAAAAAAAAAAAAAAAAAS20qhQEAAAAAAAAAAAAAAAAAAAAAAAAj950wrhOBAAAAAAAAAAAAAAAAAAAAAFp98vtxumUAAAAAAAAAAAAAAAAAAAAAEo97wq05zcAAAAA",
  },
} as const

export type IdentityPattern =
  keyof typeof PRODUCT_DOT_PATTERNS | keyof typeof PORTRAIT_DOT_PATTERNS

export type IdentityDotPattern = Readonly<{ columns: number; levels: string }>

const patterns: Readonly<Record<string, IdentityDotPattern>> = {
  ...PRODUCT_DOT_PATTERNS,
  ...PORTRAIT_DOT_PATTERNS,
}

export function getIdentityDotPattern(
  pattern: IdentityPattern
): IdentityDotPattern {
  return patterns[pattern]
}

export function isIdentityPattern(value: unknown): value is IdentityPattern {
  return typeof value === "string" && Object.hasOwn(patterns, value)
}
